# start with following cmd:
#  docker-compose -f docker-compose.yml -f docker-compose.user.yml up -d

version: '3'
services:
    postgres:
        volumes:
            - /Users/junyong/Develop/docker_data/{{cookiecutter.project_name}}_db:/var/lib/postgresql/data

    webserver:
        volumes:
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/dags:/usr/local/airflow/dags
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/notebooks:/usr/local/airflow/jupyter
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/logs:/usr/local/airflow/logs
            - /Users/junyong/tmp/hackathon/百威/Hackathon/Hackathon - STR Misreporting/May/airflow_data:/usr/local/airflow/data

    scheduler:
        volumes:
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/dags:/usr/local/airflow/dags
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/logs:/usr/local/airflow/logs
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/notebooks:/usr/local/airflow/jupyter
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/src:/usr/local/airflow/src
            - /Users/junyong/tmp/hackathon/百威/Hackathon/Hackathon - STR Misreporting/May/airflow_data:/usr/local/airflow/data

    worker:
        volumes:
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/dags:/usr/local/airflow/dags
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/logs:/usr/local/airflow/logs
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/notebooks:/usr/local/airflow/jupyter
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/src:/usr/local/airflow/src
            - /Users/junyong/tmp/hackathon/百威/Hackathon/Hackathon - STR Misreporting/May/airflow_data:/usr/local/airflow/data

    airflow_jupyter:
        volumes:
            - /Users/junyong/tmp/hackathon/百威/Hackathon/Hackathon - STR Misreporting/May/airflow_data:/usr/local/airflow/data
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/notebooks:/home/jovyan/work
            - /Users/junyong/Develop/git/github/test/{{cookiecutter.project_name}}/src:/home/src

    airflow_nginx:
        volumes:
            - /Users/junyong/Develop/docker_data/airflow_nginx:/etc/nginx/logs/
