version: '3'
services:
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build: airflow
        environment:
            - LOAD_EX=n
            - DATA_PATH=/usr/local/airflow/data
            # The following two PATH must end with /
            - CODE_ROOT_PATH=/usr/local/airflow/
            - JUPYTER_ROOT_PATH=/usr/local/airflow/jupyter/
            - AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=60
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    airflow_jupyter:
        build: jupyter
        environment:
            - GRANT_SUDO=yes
            - DATA_PATH=/usr/local/airflow/data
            - CODE_ROOT_PATH=/usr/local/airflow/
        command: start-notebook.sh

    airflow_nginx:
        build: nginx
        depends_on:
            - webserver
            - airflow_jupyter
        links:
            - webserver
            - airflow_jupyter
        ports:
            - "8090:80"
        command: [nginx, '-g', 'daemon off;']
